# Generated by Django 3.2 on 2021-04-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210418_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Vegitables', 'Vegitables'), ('Grains', 'Grains'), ('Fruits', 'Fruits')], max_length=200, null=True),
        ),
    ]
