# Generated by Django 3.2 on 2021-04-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingadress',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
